In [1]:
import numpy as np
import pandas as pd
from pyproj import Geod
from tqdm.notebook import tqdm

In [2]:
res = pd.read_csv("../data/sel_loc_all_app20232024_sp080_0430_074707.csv")
geod = Geod(ellps="WGS84")
az = np.r_[0, 45 + np.arange(4)*90]
dist = np.r_[0, np.sqrt(2)*50*np.ones([4])]
df_list = [None] * res.shape[0]
res.drop(["row","col"], axis=1, inplace=True)
for i in tqdm(range(res.shape[0])):
    df = pd.concat([res.loc[i:i]]*5).reset_index(drop=True)
    df.loc[:, ["lon","lat"]] = np.transpose(np.array(geod.fwd(df.lon, df.lat, az, dist)[:2]))
    df["point"] = np.arange(df.shape[0])
    df["id"] = [f"{df.person_code[k]}_d{df.t[k]:02}_s{df.exp_id[k]}_p{df.point[k]}" for k in range(df.shape[0])]
    df_list[i] = df

  0%|          | 0/2510 [00:00<?, ?it/s]

In [3]:
res_ext = pd.concat(df_list)
display(res_ext.head(20))
res_ext.to_csv("../data/sel_loc_ext_all_app20232024_sp080_0430_074707.csv", index=False)

t person_code  sci_id  exp_id        lat        lon  point            id
0  0          ON       0       0  62.368809  26.055851      0  ON_d00_s0_p0
1  0          ON       0       0  62.369258  26.056817      1  ON_d00_s0_p1
2  0          ON       0       0  62.368360  26.056817      2  ON_d00_s0_p2
3  0          ON       0       0  62.368360  26.054885      3  ON_d00_s0_p3
4  0          ON       0       0  62.369258  26.054885      4  ON_d00_s0_p4
0  0          ON       0       1  62.375018  26.060154      0  ON_d00_s1_p0
1  0          ON       0       1  62.375466  26.061120      1  ON_d00_s1_p1
2  0          ON       0       1  62.374569  26.061120      2  ON_d00_s1_p2
3  0          ON       0       1  62.374569  26.059188      3  ON_d00_s1_p3
4  0          ON       0       1  62.375466  26.059188      4  ON_d00_s1_p4
0  0          ON       0       2  62.427349  25.984847      0  ON_d00_s2_p0
1  0          ON       0       2  62.427798  25.985815      1  ON_d00_s2_p1
2  0          ON       0       2  62.426901  25.985815      2  ON_d00_s2_p2
3  0          ON       0       2  62.426901  25.983879      3  ON_d00_s2_p3
4  0          ON       0       2  62.427798  25.983879      4  ON_d00_s2_p4
0  0          ON       0       3  62.359052  26.077367      0  ON_d00_s3_p0
1  0          ON       0       3  62.359501  26.078333      1  ON_d00_s3_p1
2  0          ON       0       3  62.358604  26.078333      2  ON_d00_s3_p2
3  0          ON       0       3  62.358604  26.076402      3  ON_d00_s3_p3
4  0          ON       0       3  62.359501  26.076402      4  ON_d00_s3_p4

In [77]:
[f"{df.person_code[k]}_d{df.t[k]:02}_s{df.exp_id[k]}_p{df.point[k]}" for k in range(df.shape[0])]

['PU_d27_s9_p0',
 'PU_d27_s9_p1',
 'PU_d27_s9_p2',
 'PU_d27_s9_p3',
 'PU_d27_s9_p4']

In [76]:
df.t[0]

27

In [50]:
np.transpose(np.array(geod.fwd(df.lon, df.lat, az, dist)[:2]))

array([[26.05585091, 62.36969593],
       [26.05681687, 62.37014456],
       [26.05681685, 62.36924731],
       [26.05488496, 62.36924731],
       [26.05488494, 62.37014456]])

In [31]:
geod.fwd(df.lon, df.lat, az_list, dist)

(array([26.05585091, 26.05681687, 26.05681685, 26.05488496, 26.05488494]),
 array([62.36969593, 62.37014456, 62.36924731, 62.36924731, 62.37014456]),
 array([ 180.        , -134.99914419,  -44.99914422,   44.99914422,
         134.99914419]))

In [16]:
res

t person_code  sci_id  exp_id        lat        lon   row   col
0      0          ON       0       0  62.369696  26.055851  3428  2500
1      0          ON       0       1  62.375018  26.055851  3422  2500
2      0          ON       0       2  62.367035  26.118248  3431  2529
3      0          ON       0       3  62.382114  26.055851  3414  2500
4      0          ON       0       4  62.380340  26.045093  3416  2495
...   ..         ...     ...     ...        ...        ...   ...   ...
2505  27          PU      16       5  60.374884  26.034335  5677  2490
2506  27          PU      16       6  60.437859  26.034335  5606  2490
2507  27          PU      16       7  60.326987  26.042941  5731  2494
2508  27          PU      16       8  60.380205  26.030031  5671  2488
2509  27          PU      16       9  60.398832  26.178494  5650  2557

[2510 rows x 8 columns]

In [25]:
df

t person_code  sci_id  exp_id        lat        lon   row   col
0  0          ON       0       0  62.369696  26.055851  3428  2500
0  0          ON       0       0  62.369696  26.055851  3428  2500
0  0          ON       0       0  62.369696  26.055851  3428  2500
0  0          ON       0       0  62.369696  26.055851  3428  2500
0  0          ON       0       0  62.369696  26.055851  3428  2500