In [ ]:
# j = 0
# plt.plot(step_vec*train_step, llh_post_mat[j]-llh_prior_mat[j])
# plt.axline([0,0], [1,0], color="red", linestyle="--")
# plt.show()

In [2]:
import pandas as pd
import os
path_project = "/scratch/project_2003104/gtikhono/realtime_birds"
df_sp = pd.read_csv(os.path.join(path_project, "data", "presence_counts.csv"))

In [3]:
df_sp_act = df_sp.loc[df_sp.p24 > 20]

In [6]:
df_sp_act.reset_index(drop=True)

species     p23     p24  p25
0             000_acanthis_flammea     942    6526    0
1           001_accipiter_gentilis    1232    1879    0
2              002_accipiter_nisus     543    1243    0
3    003_acrocephalus_arundinaceus     401     460    0
4       004_acrocephalus_dumetorum    9155   15051    0
..                             ...     ...     ...  ...
191          250_turdus_philomelos   22290   28050    0
192             251_turdus_pilaris  109681  205757    0
193          253_turdus_viscivorus    1031    2993    0
194                 255_uria_aalge      12      72    0
195          256_vanellus_vanellus    4888   10786    0

[196 rows x 4 columns]

In [ ]:
df_sp_act.to_csv("path_project")

In [14]:
df_sp.p23.sum()

3164691

In [13]:
import numpy as np
np.minimum(df_sp.p24.values, 1)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0])

In [17]:
import pickle
sp = "000_acanthis_flammea"
path_sp = "/scratch/project_2003104/gtikhono/realtime_birds/data/species/000_acanthis_flammea"
with open(os.path.join(path_sp, sp+"_prior.pickle"), 'rb') as handle:
    species = pickle.load(handle)

In [19]:
species.loc[135:145]

y  prior.m   prior.s   prior.d  prior.d.a  prior.d.b  prior.d.u  \
135  0.0      1.0  0.114095  0.062283   0.062283        0.0        0.0   
136  0.0      1.0  0.112031  0.072253   0.072253        0.0        0.0   
137  0.0      1.0  0.111899  0.072253   0.072253        0.0        0.0   
138  0.0      1.0  0.095934  0.025807   0.025807        0.0        0.0   
139  0.0      1.0  0.095171  0.054542   0.054542        0.0        0.0   
140  0.0      1.0  0.075932       NaN        NaN        NaN        0.0   
141  0.0      1.0  0.074597       NaN        NaN        NaN        0.0   
142  0.0      1.0  0.070285  1.000000   1.000000        0.0        0.0   
143  0.0      1.0  0.069835  0.004194   0.004194        0.0        0.0   
144  0.0      1.0  0.340454  0.127341   0.127341        0.0        0.0   
145  0.0      1.0  0.335477  0.127341   0.127341        0.0        0.0   

     complete  
135      True  
136      True  
137      True  
138      True  
139      True  
140     False  
141     False  
142      True  
143      True  
144      True  
145      True

In [34]:
import warnings
with warnings.catch_warnings():
    warnings.filterwarnings("ignore", "Mean of empty slice")
    np.nanmean(np.array([np.nan]))
    np.zeros([2]) / np.zeros([2])
np.nanmean(np.array([np.nan]))

/tmp/gtikhono/4393708/ipykernel_4182416/2095550949.py:3: RuntimeWarning: Mean of empty slice
  np.nanmean(np.array([np.nan]))
/tmp/gtikhono/4393708/ipykernel_4182416/2095550949.py:4: RuntimeWarning: invalid value encountered in divide
  np.zeros([2]) / np.zeros([2])
/tmp/gtikhono/4393708/ipykernel_4182416/2095550949.py:5: RuntimeWarning: Mean of empty slice
  np.nanmean(np.array([np.nan]))


nan

In [25]:
import os
import tqdm
import shutil
import pyreadr
import pickle
import pandas as pd
import cmd
import numpy as np

path_project = "/scratch/project_2003104/gtikhono/realtime_birds"
dir_orig_data = "orig_data"
dir_data = "data/species"
displaywidth = 100

path_priors = os.path.join(path_project, dir_orig_data, "prior predictions")
fn = os.listdir(path_priors)
fn.sort()
cli = cmd.Cmd()
cli.columnize(fn, displaywidth=displaywidth)
print("reading meta.RData", flush=True)
meta = pyreadr.read_r(os.path.join(path_project, dir_orig_data, "meta.RData"))
XData = meta["XData"]
print("computing d23, d24, d25", flush=True)
d23 = (XData["j.date"] >= 1+0*365) & (XData["j.date"] <= 1*365)
d24 = (XData["j.date"] >= 1+1*365) & (XData["j.date"] <= 2*365)
d25 = (XData["j.date"] >= 1+2*365) & (XData["j.date"] <= 3*365)
df_sp = pd.DataFrame(index=np.arange(len(fn)), columns=["species", "p23", "p24", "p25"])
for j, f in enumerate(tqdm.tqdm(fn[26:27])):
    x = f.rfind("_")
    sp = f[:x]
    sp_new = "%.3d_%s" % (j, sp.lower().replace(" ", "_"))
    df_sp.loc[j, "species"] = sp_new
    species_raw = pyreadr.read_r(os.path.join(path_priors, sp+"_prior.RData"))
    species = pd.concat([species_raw[k] for k in species_raw.keys()], axis=1)
    species["complete"] = species.isna().sum(axis=1) == 0

Acanthis flammea_prior.RData               Larus argentatus_prior.RData         
Accipiter gentilis_prior.RData             Larus canus_prior.RData              
Accipiter nisus_prior.RData                Larus fuscus_prior.RData             
Acrocephalus arundinaceus_prior.RData      Larus marinus_prior.RData            
Acrocephalus dumetorum_prior.RData         Limosa lapponica_prior.RData         
Acrocephalus palustris_prior.RData         Limosa limosa_prior.RData            
Acrocephalus schoenobaenus_prior.RData     Linaria cannabina_prior.RData        
Acrocephalus scirpaceus_prior.RData        Linaria flavirostris_prior.RData     
Actitis hypoleucos_prior.RData             Locustella fluviatilis_prior.RData   
Aegithalos caudatus_prior.RData            Locustella luscinioides_prior.RData  
Aegolius funereus_prior.RData              Locustella naevia_prior.RData        
Alauda arvensis_prior.RData                Lophophanes cristatus_prior.RData    
Alca torda_prior.RData      

100%|██████████| 1/1 [00:11<00:00, 11.05s/it]


In [60]:
sp_new = "%.3d_%s" % (j, sp.lower().replace(" ", "_"))
df_sp.loc[j, "species"] = sp_new
species_raw = pyreadr.read_r(os.path.join(path_priors, sp+"_prior.RData"))
species = pd.concat([species_raw[k] for k in species_raw.keys()], axis=1)
species["complete"] = species.isna().sum(axis=1) == 0

In [50]:
species.loc[species["complete"]].y

0          0.0
1          0.0
2          0.0
3          0.0
4          0.0
          ... 
8820765    0.0
8820766    0.0
8820767    0.0
8820768    0.0
8820769    0.0
Name: y, Length: 8570192, dtype: float64

In [61]:
from scipy.stats import norm as scipy_norm
species["prior.s.L"] = pd.Series(scipy_norm.ppf(species["prior.s"]), index=species["prior.s"].index)
species["complete1"] = species.isna().sum(axis=1) == 0

print(((species.y==1) & d23).sum())
print(((species.y==1) & species.complete & d23).sum())
print(((species.y==1) & species.complete1 & d23).sum())

27469
27042
27042


In [24]:
with pd.option_context( 'display.max_rows', 500):
    df = pd.read_csv(os.path.join(path_project, "data", "presence_counts.csv"))
    display(df)

species     p23     p24  p25
0                 000_acanthis_flammea     942    6526    0
1               001_accipiter_gentilis    1232    1879    0
2                  002_accipiter_nisus     543    1243    0
3        003_acrocephalus_arundinaceus     401     460    0
4           004_acrocephalus_dumetorum    9155   15051    0
5           005_acrocephalus_palustris     849    1348    0
6       006_acrocephalus_schoenobaenus   12290   18315    0
7          007_acrocephalus_scirpaceus     709     665    0
8               008_actitis_hypoleucos   27032   42962    0
9              009_aegithalos_caudatus    2348    7392    0
10               010_aegolius_funereus     214     333    0
11                 011_alauda_arvensis   12767   30186    0
12                      012_alca_torda       2      10    0
13                   013_alcedo_atthis       1       7    0
14                      014_anas_acuta       0       2    0
15                     015_anas_crecca     935    3070    0
16              016_anas_platyrhynchos    1284    3367    0
17                 017_anser_albifrons     343    2831    0
18                     018_anser_anser     994    2524    0
19            019_anser_brachyrhynchus       0       1    0
20                020_anser_erythropus       1       6    0
21                   021_anser_fabalis     787    3689    0
22               022_anthus_campestris       0       2    0
23                 023_anthus_cervinus       1      11    0
24                 024_anthus_petrosus      10      51    0
25                025_anthus_pratensis     947    2465    0
26                026_anthus_trivialis   27469   39208    0
27                       027_apus_apus   17655   37724    0
28               028_aquila_chrysaetos      21      36    0
29                      029_ardea_alba       0       3    0
30                   030_ardea_cinerea     910    2368    0
31              031_arenaria_interpres       4       7    0
32                   032_asio_flammeus       4       5    0
33                       033_asio_otus     645    1775    0
34                   034_aythya_ferina       1      11    0
35                 035_aythya_fuligula      12      30    0
36             036_bombycilla_garrulus    2499    3504    0
37              037_botaurus_stellaris    1168    3396    0
38                 038_branta_bernicla       0       0    0
39               039_branta_canadensis    1705    4450    0
40                040_branta_leucopsis    9013   25466    0
41                       041_bubo_bubo      12      47    0
42                 042_bubo_scandiacus       0       0    0
43              043_bucephala_clangula    1271    4097    0
44                     044_buteo_buteo    2285    5992    0
45                   045_buteo_lagopus     185     128    0
46            046_calcarius_lapponicus      19      64    0
47                   047_calidris_alba       0       2    0
48                 048_calidris_alpina       0      13    0
49                049_calidris_canutus      10      21    0
50            050_calidris_falcinellus       1       2    0
51             051_calidris_ferruginea       1       5    0
52               052_calidris_maritima       0       2    0
53                 053_calidris_minuta       0       2    0
54             054_calidris_temminckii       4      23    0
55           055_caprimulgus_europaeus    1075    2016    0
56             056_carduelis_carduelis   17172   36659    0
57           057_carpodacus_erythrinus   23044   33086    0
58                  058_cepphus_grylle      21      46    0
59              059_certhia_familiaris    9669   23380    0
60               060_charadrius_dubius     220     507    0
61            061_charadrius_hiaticula      66     144    0
62           062_charadrius_morinellus       3      13    0
63                063_chlidonias_niger       4       7    0
64                 064_chloris_chloris   78971  156204    0
65      065_chroicocephalus_ridibundus   28965   70573    0
66         

In [1]:
import numpy as np
A = np.reshape(np.arange(24), [2,3,4])
display(A)
B = np.array([[0,1],[1,0]])
A[:2,:2,1] &= np.matrix([[1,0],[0,1]])
A

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

array([[[ 0,  1,  2,  3],
        [ 4,  0,  6,  7],
        [ 8,  9, 10, 11]],

       [[12,  0, 14, 15],
        [16,  1, 18, 19],
        [20, 21, 22, 23]]])

In [6]:
B = 2*np.ones([3,4])

In [7]:
A + B

array([[[ 2.,  3.,  4.,  5.],
        [ 6.,  2.,  8.,  9.],
        [10., 11., 12., 13.]],

       [[14.,  2., 16., 17.],
        [18.,  3., 20., 21.],
        [22., 23., 24., 25.]]])

In [9]:
100**2 * 200 * 200 / 1e6

400.0